<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="drone">\
    
    <xacro:include filename = "inertial_macros.xacro"/>
    <xacro:include filename = "drone_macros.xacro"/>

    <!-- MATERIAL -->

    <material name = "white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <!-- PARAMETERS -->

    <xacro:property name = "base_length" value = "0.3"/>
    <xacro:property name = "base_width" value = "0.3"/>
    <xacro:property name = "base_height" value = "0.1"/>
    <xacro:property name = "rotor_radius" value = "0.05"/>
    <xacro:property name = "rotor_length" value = "0.05"/>
    <xacro:property name = "mass" value = "1.0"/>
    <xacro:property name = "wing_pos" value = "${base_height/2+0.02}"/>


    <!-- BASE_LINK -->

    <link name="base_link">
        
    </link>


    <!-- BODY_LINK -->

    <joint name="body_joint" type="fixed">
        <parent link="base_link"/>
        <child link="body_link"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="body_link">
        <visual>
            <origin xyz="0 0 ${base_height/2}"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <material name = "white"/>
        </visual>

        <collision>
            <origin xyz="0 0 ${base_height/2}"/>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>    
        </collision>

        <xacro:inertial_box mass = "${mass}" x = "${base_length}" y = "${base_width}" z = "${base_height}">
            <origin xyz="0 0 ${base_height/2}" rpy = "0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference = "body_link">
        Gazebo/White
    </gazebo>

    
    <!-- Bar 1 -->

    <xacro:bar name="bar1" parent="body_link" angle="${pi/4}" pos="0.3 0 ${wing_pos}" size="0.3 0.08 0.03"></xacro:bar>

    <!-- Rotor 1 -->

    <xacro:rotor num="1" parent="bar1" radius="${rotor_radius}" length="${rotor_length}" wing_pos="${wing_pos}"></xacro:rotor>

    <!-- Bar 2 -->

    <xacro:bar name="bar2" parent="body_link" angle="${3*pi/4}" pos="0.3 0 ${wing_pos}" size="0.3 0.08 0.03"></xacro:bar>


    <!-- Rotor 2 -->

    <xacro:rotor num="2" parent="bar2" radius="${rotor_radius}" length="${rotor_length}" wing_pos="${wing_pos}"></xacro:rotor>

    <!-- Bar 3 -->

    <xacro:bar name="bar3" parent="body_link" angle="${-3*pi/4}" pos="0.3 0 ${wing_pos}" size="0.3 0.08 0.03"></xacro:bar>

    <!-- Rotor 3 -->

    <xacro:rotor num="3" parent="bar3" radius="${rotor_radius}" length="${rotor_length}" wing_pos="${wing_pos}"></xacro:rotor>

    <!-- Bar 4 -->

    <xacro:bar name="bar4" parent="body_link" angle="${-pi/4}" pos="0.3 0 ${wing_pos}" size="0.3 0.08 0.03"></xacro:bar>

    <!-- Rotor 4 -->

    <xacro:rotor num="4" parent="bar4" radius="${rotor_radius}" length="${rotor_length}" wing_pos="${wing_pos}"></xacro:rotor>

</robot>
