<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name = "mass" value = "1.0"/>

    <!-- Bar -->
    
    <xacro:macro name="bar" params="name parent angle pos size ">
        <joint name="${name}_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="${name}"/>
            <origin xyz="0 0 0" rpy="0 0 ${angle}"/>
        </joint>

        <link name="${name}">
            <visual>
                <origin xyz="${pos}"/>
                <geometry>
                    <box size="${size}"/>
                </geometry>
                <material name="orange"/>
            </visual>

            <collision>
                <origin xyz="${pos}"/>
                <geometry>
                    <box size="${size}"/>
                </geometry>
            </collision>
        </link>

        <xacro:inertial_box mass="${mass}" x="${size[0]}" y="${size[1]}" z="${size[2]}"></xacro:inertial_box>

        <gazebo reference="${name}">
            <material>
                Gazebo/Orange
            </material>
        </gazebo> 
    </xacro:macro>
    

    <!-- Rotor -->

    <xacro:macro name="rotor" params="num parent radius length wing_pos">
        <joint name="rotor${num}_joint" type="continuous">
            <parent link="${parent}"/>
            <child link="rotor${num}"/>
            <origin xyz="${0.45-radius} 0.0 ${wing_pos +0.015}"/>
            <axis xyz="0 0 ${-1 if num %2 == 1 else 1}"/>
        </joint>

        <link name="rotor${num}">
            <visual>
                <origin xyz="0 0 ${length/2}"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name = "blue"/>
            </visual>

            <collision>
                <origin xyz="0 0 ${length/2}"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
            </collision>
        </link>

        <xacro:inertial_cylinder mass="${mass}" length="${length}" radius="${radius}">
        </xacro:inertial_cylinder>

        <gazebo>
            <material>
                Gazebo/Blue
            </material>
        </gazebo>
    </xacro:macro>

</robot>
